const universities = [
  "Centrale Lyon",
  "École centrale d'électronique",
  "École normale supérieure de Lyon",
  "Institut national d'histoire de l'art",
  "Institut supérieur du bâtiment et des travaux publics",
  "Ecole Supérieur d'Ingénieurs en Electronique et Electrotechnique",
  "Neoma Business School",
  "Université Paris-Saclay",
  "ECAM-EPMI",
  "École nationale supérieure d'architecture de Paris-Belleville",
  "École nationale supérieure maritime",
  "École pour l'informatique et les techniques avancées",
  "Institut supérieur d'agriculture de Lille",
  "Institut régional du travail social de Champagne-Ardennes",
  "Sorbonne Université",
  "Université de Bordeaux",
  "Université de Strasbourg",
  "Université d'Évry-Val-d'Essonne",
  "Université Lumière - Lyon 2",
  "Université Paul-Valéry - Montpellier 3",
  "Yncréa Méditerranée",
  "École supérieure d'art et design Le Havre-Rouen",
  "Institut supérieur de l'électronique et du numérique de Brest",
  "Université de Poitiers",
  "Université de Reims Champagne-Ardenne",
  "Université de Rennes",
  "Edhec Business School"
];
